# All values in no of frames
BACKGROUND_COLOR: dimgray
FRAME_RATE: 60
SCREEN_RES: [1280, 720]
FIX_CROSS_TIME: 30
NO_TRAINING_TRIALS: [5, 1]
NO_BLOCKS: 10
TRIALS_IN_BLOCK: 10
TRAINING_TRIALS: 10
FIX_CROSS_COLOR: pink
STIM_LETTERS: ["A","E","I","U","X","P","L","Z"]
STIM_NUMBERS: ["2","3","4","5","6","7","8","9"]
STIM_CUE: ["LITERA", "CYFRA"]
STIM_SIZE: 50
STIM_TIME: 18
REACTION_TIME: 300
MASK_TIME: 90
REACTION_KEYS: ['z','m']
STIM_COLOR: black
