# All values in no of frames
BACKGROUND_COLOR: [46, 46, 46]
FRAME_RATE: 60
SCREEN_RES: [2160, 1440]   
FIX_CROSS_TIME: 30 
NO_TRAINING_TRIALS: [5, 1]
NO_BLOCKS: 10
TRIALS_IN_BLOCK: 10
TRAINING_TRIALS: 10
FIX_CROSS_COLOR: [255, 135, 240]
STIM_LETTERS: ["A","E","I","U","X","P","L","Z"]
STIM_NUMBERS: ["2","3","4","5","6","7","8","9"]
STIM_CUE: ["LITERA", "CYFRA"]
STIM_SIZE: 24
#STIM_SHIFT: 600
STIM_TIME: 18
REACTION_TIME: 300
MASK_TIME: 90
REACTION_KEYS: ['z','m']
#REACTION_KEYS_SEP: 30
STIM_COLOR: [253, 253, 253]
